### ISSUE TITLE
Unrecognized option --threshold when using ReportType.COVERALLS

### ISSUE THREAD

**Issue by nlowe** [nlowe/Cake.MiniCover#4]
```csharp
Specify --help for a list of available options and commands.

Unhandled Exception: Microsoft.Extensions.CommandLineUtils.CommandParsingException: Unrecognized option '--threshold'
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.HandleUnexpectedArg(CommandLineApplication command, String[] args, Int32 index, String argTypeName)
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at MiniCover.Program.Main(String[] args)
```

**Comment by nlowe** [comment]
A pre-release (`0.29.0-next20180721071547` is available on NuGet) with a fix for this.
